PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gaf: <http://groundedannotationframework.org/gaf#>
PREFIX grasp: <http://groundedannotationframework.org/grasp#>

select ?statement where {
    BIND(<%s> AS ?author1)

    ?statement rdf:type gaf:Assertion .
    ?statement gaf:denotedBy ?m .
    ?m grasp:wasAttributedTo ?author1 .

}
GROUP BY ?statement HAVING (COUNT(distinct ?m) = 1)