# pepper.knowledge package
OBJECT_INFO = {
    'home appliance': {'building': False, 'moving': False}, 'swim cap': {'building': False, 'moving': True},
    'office building': {'building': True, 'moving': False}, 'skis': {'building': False, 'moving': False},
    'bell pepper': {'building': False, 'moving': True}, 'crocodile': {'building': False, 'moving': True},
    'loveseat': {'building': False, 'moving': False}, 'musical keyboard': {'building': False, 'moving': False},
    'chair': {'building': False, 'moving': True}, 'dumbbell': {'building': False, 'moving': True},
    'milk': {'building': False, 'moving': False}, 'ceiling fan': {'building': False, 'moving': True},
    'grape': {'building': False, 'moving': False}, 'mixing bowl': {'building': False, 'moving': False},
    'tv': {'building': False, 'moving': False}, 'swan': {'building': False, 'moving': True},
    'dairy': {'building': False, 'moving': False}, 'artichoke': {'building': False, 'moving': False},
    'trousers': {'building': False, 'moving': True}, 'jet ski': {'building': False, 'moving': False},
    'digital clock': {'building': False, 'moving': False}, 'dragonfly': {'building': False, 'moving': True},
    'fax': {'building': False, 'moving': False}, 'woman': {'building': False, 'moving': True},
    'ladle': {'building': False, 'moving': False}, 'dessert': {'building': False, 'moving': False},
    'human hand': {'building': False, 'moving': True}, 'screwdriver': {'building': False, 'moving': False},
    'vase': {'building': False, 'moving': False}, 'spoon': {'building': False, 'moving': False},
    'tablet computer': {'building': False, 'moving': True}, 'fireplace': {'building': False, 'moving': False},
    'segway': {'building': False, 'moving': False}, 'stapler': {'building': False, 'moving': False},
    'whisk': {'building': False, 'moving': False}, 'parrot': {'building': False, 'moving': True},
    'asparagus': {'building': False, 'moving': False}, 'punching bag': {'building': False, 'moving': True},
    'dinosaur': {'building': False, 'moving': True}, 'saxophone': {'building': False, 'moving': False},
    'mammal': {'building': False, 'moving': True}, 'light bulb': {'building': False, 'moving': True},
    'snowmobile': {'building': False, 'moving': False}, 'carnivore': {'building': False, 'moving': True},
    'bicycle': {'building': False, 'moving': False}, 'tea': {'building': False, 'moving': False},
    'sports uniform': {'building': False, 'moving': True}, 'lavender': {'building': False, 'moving': False},
    'horn': {'building': False, 'moving': False}, 'nail': {'building': False, 'moving': False},
    'personal care': {'building': False, 'moving': False}, 'fast food': {'building': False, 'moving': False},
    'panda': {'building': False, 'moving': True}, 'power plugs and sockets': {'building': False, 'moving': True},
    'clock': {'building': False, 'moving': False}, 'stool': {'building': False, 'moving': False},
    'paddle': {'building': False, 'moving': False}, 'medical equipment': {'building': False, 'moving': False},
    'unicycle': {'building': False, 'moving': False}, 'bird': {'building': False, 'moving': True},
    'facial tissue holder': {'building': False, 'moving': True}, 'kangaroo': {'building': False, 'moving': True},
    'mule': {'building': False, 'moving': True}, 'remote control': {'building': False, 'moving': False},
    'indoor rower': {'building': False, 'moving': True}, 'sink': {'building': False, 'moving': False},
    'pancake': {'building': False, 'moving': False}, 'goldfish': {'building': False, 'moving': True},
    'dice': {'building': False, 'moving': False}, 'box': {'building': False, 'moving': False},
    'boy': {'building': False, 'moving': True}, 'tortoise': {'building': False, 'moving': True},
    'sports ball': {'building': False, 'moving': True}, 'hamster': {'building': False, 'moving': True},
    'raccoon': {'building': False, 'moving': True}, 'pillow': {'building': False, 'moving': False},
    'musical instrument': {'building': False, 'moving': True}, 'roller skates': {'building': False, 'moving': True},
    'apple': {'building': False, 'moving': False}, 'radish': {'building': False, 'moving': False},
    'traffic sign': {'building': False, 'moving': False}, 'cricket ball': {'building': False, 'moving': True},
    'snowboard': {'building': False, 'moving': False}, 'bicycle wheel': {'building': False, 'moving': False},
    'sun hat': {'building': False, 'moving': True}, 'duck': {'building': False, 'moving': True},
    'hamburger': {'building': False, 'moving': False}, 'kitchen appliance': {'building': False, 'moving': False},
    'waffle iron': {'building': False, 'moving': False}, 'bottle opener': {'building': False, 'moving': True},
    'humidifier': {'building': False, 'moving': False}, 'frog': {'building': False, 'moving': True},
    'camera': {'building': False, 'moving': False}, 'crab': {'building': False, 'moving': True},
    'vehicle': {'building': False, 'moving': False}, 'light switch': {'building': False, 'moving': True},
    'limousine': {'building': False, 'moving': False}, 'auto part': {'building': False, 'moving': False},
    'human arm': {'building': False, 'moving': True}, 'ladybug': {'building': False, 'moving': True},
    'sushi': {'building': False, 'moving': False}, 'door': {'building': False, 'moving': False},
    'porch': {'building': False, 'moving': False}, 'envelope': {'building': False, 'moving': False},
    'bronze sculpture': {'building': False, 'moving': False}, 'missile': {'building': False, 'moving': False},
    'flag': {'building': False, 'moving': False}, 'train': {'building': False, 'moving': False},
    'armadillo': {'building': False, 'moving': True}, 'rabbit': {'building': False, 'moving': True},
    'salad': {'building': False, 'moving': False}, 'car': {'building': False, 'moving': False},
    'chisel': {'building': False, 'moving': False}, 'worm': {'building': False, 'moving': True},
    'cat': {'building': False, 'moving': True}, 'donut': {'building': False, 'moving': False},
    'drill': {'building': False, 'moving': True}, 'shark': {'building': False, 'moving': True},
    'headphones': {'building': False, 'moving': False}, 'tap': {'building': False, 'moving': False},
    'dolphin': {'building': False, 'moving': True}, 'parachute': {'building': False, 'moving': False},
    'drawer': {'building': False, 'moving': True}, 'carrot': {'building': False, 'moving': False},
    'paper towel': {'building': False, 'moving': False}, 'mixer': {'building': False, 'moving': False},
    'airplane': {'building': False, 'moving': False}, 'woodpecker': {'building': False, 'moving': True},
    'clothing': {'building': False, 'moving': True}, 'centipede': {'building': False, 'moving': True},
    'skirt': {'building': False, 'moving': True}, 'magpie': {'building': False, 'moving': True},
    'rhinoceros': {'building': False, 'moving': True}, 'lamp': {'building': False, 'moving': False},
    'sword': {'building': False, 'moving': False}, 'elephant': {'building': False, 'moving': True},
    'frying pan': {'building': False, 'moving': False}, 'cheetah': {'building': False, 'moving': True},
    'goat': {'building': False, 'moving': True}, 'pizza': {'building': False, 'moving': False},
    'plant': {'building': False, 'moving': True}, 'sandwich': {'building': False, 'moving': False},
    'cupboard': {'building': False, 'moving': False}, 'briefcase': {'building': False, 'moving': False},
    'cocktail': {'building': False, 'moving': False}, 'soap dispenser': {'building': False, 'moving': True},
    'moths and butterflies': {'building': False, 'moving': True}, 'toilet paper': {'building': False, 'moving': False},
    'taco': {'building': False, 'moving': True}, 'cabbage': {'building': False, 'moving': False},
    'popcorn': {'building': False, 'moving': False}, 'fedora': {'building': False, 'moving': True},
    'tomato': {'building': False, 'moving': False}, 'oboe': {'building': False, 'moving': False},
    'salt and pepper shakers': {'building': False, 'moving': True}, 'croissant': {'building': False, 'moving': False},
    'wheelchair': {'building': False, 'moving': False}, 'harbor seal': {'building': False, 'moving': True},
    'volleyball': {'building': False, 'moving': False}, 'beehive': {'building': False, 'moving': False},
    'mango': {'building': False, 'moving': False}, 'truck': {'building': False, 'moving': False},
    'wrench': {'building': False, 'moving': False}, 'ambulance': {'building': False, 'moving': False},
    'necklace': {'building': False, 'moving': False}, 'egg': {'building': False, 'moving': False},
    'wine': {'building': False, 'moving': False}, 'antelope': {'building': False, 'moving': True},
    'owl': {'building': False, 'moving': True}, 'muffin': {'building': False, 'moving': False},
    'canary': {'building': False, 'moving': True}, 'spatula': {'building': False, 'moving': False},
    'jacuzzi': {'building': False, 'moving': False}, 'motorcycle': {'building': False, 'moving': False},
    'oven': {'building': False, 'moving': False}, 'keyboard': {'building': False, 'moving': False},
    'dagger': {'building': False, 'moving': False}, 'pencil sharpener': {'building': False, 'moving': False},
    'guacamole': {'building': False, 'moving': False}, 'accordion': {'building': False, 'moving': False},
    'willow': {'building': False, 'moving': False}, 'houseplant': {'building': False, 'moving': False},
    'backpack': {'building': False, 'moving': False}, 'submarine sandwich': {'building': False, 'moving': False},
    'window': {'building': False, 'moving': False}, 'vehicle registration plate': {'building': False, 'moving': False},
    'orange': {'building': False, 'moving': False}, 'tiara': {'building': False, 'moving': True},
    'coffee': {'building': False, 'moving': False}, 'animal': {'building': False, 'moving': True},
    'food processor': {'building': False, 'moving': True}, 'food': {'building': False, 'moving': False},
    'tennis racket': {'building': False, 'moving': False}, 'caterpillar': {'building': False, 'moving': True},
    'giraffe': {'building': False, 'moving': True}, 'snake': {'building': False, 'moving': True},
    'horizontal bar': {'building': False, 'moving': False}, 'bread': {'building': False, 'moving': False},
    'human beard': {'building': False, 'moving': True}, 'convenience store': {'building': False, 'moving': False},
    'filing cabinet': {'building': False, 'moving': False}, 'jellyfish': {'building': False, 'moving': True},
    'lantern': {'building': False, 'moving': False}, 'picture frame': {'building': False, 'moving': False},
    'microwave oven': {'building': False, 'moving': False}, 'house': {'building': True, 'moving': False},
    'fish': {'building': False, 'moving': True}, 'torch': {'building': False, 'moving': False},
    'spider': {'building': False, 'moving': True}, 'cooking spray': {'building': False, 'moving': False},
    'waffle': {'building': False, 'moving': False}, 'goose': {'building': False, 'moving': True},
    'zebra': {'building': False, 'moving': True}, 'beetle': {'building': False, 'moving': True},
    'girl': {'building': False, 'moving': True}, 'ice cream': {'building': True, 'moving': False},
    'harp': {'building': False, 'moving': False}, 'marine invertebrates': {'building': False, 'moving': True},
    'flower': {'building': False, 'moving': False}, 'container': {'building': False, 'moving': False},
    'lipstick': {'building': False, 'moving': False}, 'tennis ball': {'building': False, 'moving': True},
    'alarm clock': {'building': False, 'moving': False}, 'fountain': {'building': False, 'moving': False},
    'ladder': {'building': False, 'moving': False}, 'eagle': {'building': False, 'moving': True},
    'umbrella': {'building': False, 'moving': False}, 'ipod': {'building': False, 'moving': False},
    'cart': {'building': False, 'moving': False}, 'cookie': {'building': False, 'moving': True},
    'van': {'building': False, 'moving': False}, 'hair dryer': {'building': False, 'moving': False},
    'dishwasher': {'building': False, 'moving': True}, 'sea lion': {'building': False, 'moving': True},
    'seahorse': {'building': False, 'moving': True}, 'snowplow': {'building': False, 'moving': False},
    'skateboard': {'building': False, 'moving': False}, 'ostrich': {'building': False, 'moving': True},
    'footwear': {'building': False, 'moving': True}, 'hedgehog': {'building': False, 'moving': True},
    'lifejacket': {'building': False, 'moving': False}, 'scarf': {'building': False, 'moving': True},
    'cheese': {'building': False, 'moving': False}, 'face powder': {'building': False, 'moving': True},
    'coffee table': {'building': False, 'moving': False}, 'maracas': {'building': False, 'moving': False},
    'sofa bed': {'building': False, 'moving': False}, 'scissors': {'building': False, 'moving': False},
    'cell phone': {'building': False, 'moving': False}, 'maple': {'building': False, 'moving': False},
    'sheep': {'building': False, 'moving': True}, 'computer monitor': {'building': False, 'moving': True},
    'horse': {'building': False, 'moving': True}, 'toy': {'building': False, 'moving': True},
    'monkey': {'building': False, 'moving': True}, 'man': {'building': False, 'moving': True},
    'banana': {'building': False, 'moving': False}, 'bow and arrow': {'building': False, 'moving': False},
    'starfish': {'building': False, 'moving': True}, 'common fig': {'building': False, 'moving': False},
    'shelf': {'building': False, 'moving': False}, 'tool': {'building': False, 'moving': True},
    'blue jay': {'building': False, 'moving': True}, 'rifle': {'building': False, 'moving': False},
    'wardrobe': {'building': False, 'moving': False}, 'hand dryer': {'building': False, 'moving': True},
    'stairs': {'building': False, 'moving': False}, 'television': {'building': False, 'moving': False},
    'golf cart': {'building': False, 'moving': False}, 'tree': {'building': False, 'moving': True},
    'french fries': {'building': False, 'moving': True}, 'bed': {'building': False, 'moving': False},
    'bee': {'building': False, 'moving': True}, 'shower': {'building': False, 'moving': True},
    'coat': {'building': False, 'moving': True}, 'human foot': {'building': False, 'moving': True},
    'sculpture': {'building': False, 'moving': False}, 'coconut': {'building': False, 'moving': False},
    'ant': {'building': False, 'moving': True}, 'juice': {'building': False, 'moving': False},
    'pastry': {'building': False, 'moving': False}, 'microphone': {'building': False, 'moving': False},
    'koala': {'building': False, 'moving': True}, 'shorts': {'building': False, 'moving': True},
    'couch': {'building': False, 'moving': False}, 'bagel': {'building': False, 'moving': False},
    'palm tree': {'building': False, 'moving': True}, 'human nose': {'building': False, 'moving': True},
    'poster': {'building': False, 'moving': True}, 'banjo': {'building': False, 'moving': False},
    'lily': {'building': False, 'moving': False}, 'honeycomb': {'building': False, 'moving': False},
    'butterfly': {'building': False, 'moving': True}, 'printer': {'building': False, 'moving': True},
    'kitchen & dining room table': {'building': False, 'moving': False},
    'plumbing fixture': {'building': False, 'moving': True}, 'invertebrate': {'building': False, 'moving': True},
    'polar bear': {'building': False, 'moving': True}, 'handbag': {'building': False, 'moving': False},
    'bowling equipment': {'building': False, 'moving': False}, 'coin': {'building': False, 'moving': False},
    'refrigerator': {'building': False, 'moving': False}, 'hot dog': {'building': False, 'moving': True},
    'seafood': {'building': False, 'moving': False}, 'dog': {'building': False, 'moving': True},
    'measuring cup': {'building': False, 'moving': False}, 'axe': {'building': False, 'moving': False},
    'mechanical fan': {'building': False, 'moving': True}, 'barrel': {'building': False, 'moving': False},
    'skunk': {'building': False, 'moving': True}, 'snowman': {'building': False, 'moving': False},
    'teddy bear': {'building': False, 'moving': True}, 'infant bed': {'building': False, 'moving': True},
    'bomb': {'building': False, 'moving': False}, 'kite': {'building': False, 'moving': True},
    'sparrow': {'building': False, 'moving': True}, 'scoreboard': {'building': False, 'moving': False},
    'training bench': {'building': False, 'moving': False}, 'picnic basket': {'building': False, 'moving': False},
    'chicken': {'building': False, 'moving': True}, 'blender': {'building': False, 'moving': False},
    'human head': {'building': False, 'moving': True}, 'snack': {'building': False, 'moving': False},
    'shellfish': {'building': False, 'moving': True}, 'tire': {'building': False, 'moving': False},
    'scorpion': {'building': False, 'moving': True}, 'bust': {'building': False, 'moving': False},
    'balance beam': {'building': False, 'moving': True}, 'piano': {'building': False, 'moving': False},
    'otter': {'building': False, 'moving': True}, 'pumpkin': {'building': False, 'moving': False},
    'porcupine': {'building': False, 'moving': True}, 'plate': {'building': False, 'moving': False},
    'sunglasses': {'building': False, 'moving': False}, 'cannon': {'building': False, 'moving': False},
    'chopsticks': {'building': False, 'moving': False}, 'watch': {'building': False, 'moving': True},
    'bear': {'building': False, 'moving': True}, 'watermelon': {'building': False, 'moving': False},
    'slow cooker': {'building': False, 'moving': False}, 'handgun': {'building': False, 'moving': False},
    'bat': {'building': False, 'moving': True}, 'jaguar': {'building': False, 'moving': True},
    'organ': {'building': False, 'moving': False}, 'sea turtle': {'building': False, 'moving': True},
    'pretzel': {'building': False, 'moving': False}, 'perfume': {'building': False, 'moving': False},
    'dog bed': {'building': False, 'moving': True}, 'pizza cutter': {'building': False, 'moving': True},
    'computer keyboard': {'building': False, 'moving': True}, 'human mouth': {'building': False, 'moving': True},
    'billiard table': {'building': False, 'moving': False}, 'lion': {'building': False, 'moving': True},
    'sewing machine': {'building': False, 'moving': True}, 'cattle': {'building': False, 'moving': True},
    'racket': {'building': False, 'moving': False}, 'hammer': {'building': False, 'moving': False},
    'cake stand': {'building': False, 'moving': False}, 'red panda': {'building': False, 'moving': True},
    'closet': {'building': False, 'moving': False}, 'sombrero': {'building': False, 'moving': True},
    'human hair': {'building': False, 'moving': True}, 'computer mouse': {'building': False, 'moving': True},
    'swimwear': {'building': False, 'moving': True}, 'mug': {'building': False, 'moving': True},
    'skyscraper': {'building': True, 'moving': False}, 'wok': {'building': False, 'moving': False},
    'baked goods': {'building': False, 'moving': False}, 'tent': {'building': False, 'moving': False},
    'cantaloupe': {'building': False, 'moving': False}, 'bicycle helmet': {'building': False, 'moving': True},
    'cocktail shaker': {'building': False, 'moving': True}, 'hiking equipment': {'building': False, 'moving': False},
    'cutting board': {'building': False, 'moving': False}, 'lynx': {'building': False, 'moving': True},
    'toothbrush': {'building': False, 'moving': False}, 'aircraft': {'building': False, 'moving': False},
    'wine glass': {'building': False, 'moving': False}, 'dress': {'building': False, 'moving': True},
    'guitar': {'building': False, 'moving': False}, 'drum': {'building': False, 'moving': True},
    'cow': {'building': False, 'moving': True}, 'baseball bat': {'building': False, 'moving': True},
    'brassiere': {'building': False, 'moving': True}, 'bookcase': {'building': False, 'moving': False},
    'wall clock': {'building': False, 'moving': False}, 'door handle': {'building': False, 'moving': False},
    'bathroom accessory': {'building': False, 'moving': True}, 'swimming pool': {'building': False, 'moving': False},
    'stretcher': {'building': False, 'moving': False}, 'pencil case': {'building': False, 'moving': True},
    'jeans': {'building': False, 'moving': True}, 'rugby ball': {'building': False, 'moving': True},
    'cabinetry': {'building': False, 'moving': False}, 'isopod': {'building': False, 'moving': True},
    'table': {'building': False, 'moving': False}, 'trumpet': {'building': False, 'moving': False},
    'boat': {'building': False, 'moving': False}, 'belt': {'building': False, 'moving': True},
    'turkey': {'building': False, 'moving': True}, 'lighthouse': {'building': False, 'moving': False},
    'watercraft': {'building': False, 'moving': False}, 'rays and skates': {'building': False, 'moving': True},
    'gondola': {'building': False, 'moving': False}, 'traffic light': {'building': False, 'moving': True},
    'plastic bag': {'building': False, 'moving': True}, 'beer': {'building': False, 'moving': False},
    'high heels': {'building': False, 'moving': True}, 'eraser': {'building': False, 'moving': False},
    'curtain': {'building': False, 'moving': False}, 'wood-burning stove': {'building': False, 'moving': False},
    'squirrel': {'building': False, 'moving': True}, 'mushroom': {'building': False, 'moving': False},
    'squash': {'building': False, 'moving': False}, 'marine mammal': {'building': False, 'moving': True},
    'brown bear': {'building': False, 'moving': True}, 'bull': {'building': False, 'moving': True},
    'corded phone': {'building': False, 'moving': False}, 'teapot': {'building': False, 'moving': False},
    'drinking straw': {'building': False, 'moving': False}, 'tank': {'building': False, 'moving': False},
    'hat': {'building': False, 'moving': True}, 'crutch': {'building': False, 'moving': False},
    'lizard': {'building': False, 'moving': True}, 'ratchet': {'building': False, 'moving': False},
    'castle': {'building': True, 'moving': False}, 'bathtub': {'building': False, 'moving': False},
    'pressure cooker': {'building': False, 'moving': False}, 'football helmet': {'building': False, 'moving': True},
    'canoe': {'building': False, 'moving': False}, 'calculator': {'building': False, 'moving': True},
    'squid': {'building': False, 'moving': True}, 'office supplies': {'building': False, 'moving': False},
    'telephone': {'building': False, 'moving': False}, 'ring binder': {'building': False, 'moving': False},
    'waste container': {'building': False, 'moving': False}, 'nightstand': {'building': False, 'moving': False},
    'gas stove': {'building': False, 'moving': False}, 'violin': {'building': False, 'moving': False},
    'mouse': {'building': False, 'moving': True}, 'hair drier': {'building': False, 'moving': False},
    'helmet': {'building': False, 'moving': True}, 'grinder': {'building': False, 'moving': False},
    'shirt': {'building': False, 'moving': True}, 'balloon': {'building': False, 'moving': False},
    'toaster': {'building': False, 'moving': True}, 'bowl': {'building': False, 'moving': False},
    'spice rack': {'building': False, 'moving': False}, 'vegetable': {'building': False, 'moving': False},
    'wheel': {'building': False, 'moving': False}, 'ball': {'building': False, 'moving': True},
    'snail': {'building': False, 'moving': True}, 'pomegranate': {'building': False, 'moving': False},
    'drink': {'building': False, 'moving': False}, 'leopard': {'building': False, 'moving': True},
    'binoculars': {'building': False, 'moving': False}, 'cowboy hat': {'building': False, 'moving': True},
    'fruit': {'building': False, 'moving': False}, 'cucumber': {'building': False, 'moving': False},
    'whale': {'building': False, 'moving': True}, 'broccoli': {'building': False, 'moving': False},
    'street light': {'building': False, 'moving': True}, 'burrito': {'building': False, 'moving': False},
    'surfboard': {'building': False, 'moving': False}, 'shotgun': {'building': False, 'moving': False},
    'weapon': {'building': False, 'moving': False}, 'person': {'building': False, 'moving': True},
    'bottle': {'building': False, 'moving': False}, 'taxi': {'building': False, 'moving': False},
    'rocket': {'building': False, 'moving': False}, 'camel': {'building': False, 'moving': True},
    'laptop': {'building': False, 'moving': False}, 'desk': {'building': False, 'moving': False},
    'goggles': {'building': False, 'moving': False}, 'fire hydrant': {'building': False, 'moving': False},
    'cat furniture': {'building': False, 'moving': True}, 'flashlight': {'building': False, 'moving': False},
    'sandal': {'building': False, 'moving': False}, 'sunflower': {'building': False, 'moving': False},
    'cup': {'building': False, 'moving': False}, 'luggage and bags': {'building': False, 'moving': True},
    'rose': {'building': False, 'moving': False}, 'bench': {'building': False, 'moving': False},
    'grapefruit': {'building': False, 'moving': False}, 'cosmetics': {'building': False, 'moving': False},
    'ski': {'building': False, 'moving': False}, 'table tennis racket': {'building': False, 'moving': False},
    'raven': {'building': False, 'moving': True}, 'stationary bicycle': {'building': False, 'moving': False},
    'ruler': {'building': False, 'moving': True}, 'miniskirt': {'building': False, 'moving': True},
    'bathroom cabinet': {'building': False, 'moving': False}, 'chainsaw': {'building': False, 'moving': False},
    'barge': {'building': False, 'moving': False}, 'potted plant': {'building': False, 'moving': True},
    'falcon': {'building': False, 'moving': True}, 'doughnut': {'building': False, 'moving': False},
    'tick': {'building': False, 'moving': True}, 'furniture': {'building': False, 'moving': False},
    'towel': {'building': False, 'moving': False}, 'glove': {'building': False, 'moving': True},
    'baseball glove': {'building': False, 'moving': True}, 'tower': {'building': False, 'moving': False},
    'zucchini': {'building': False, 'moving': False}, 'doll': {'building': False, 'moving': True},
    'crown': {'building': False, 'moving': True}, 'lobster': {'building': False, 'moving': True},
    'candy': {'building': False, 'moving': False}, 'mirror': {'building': False, 'moving': False},
    'billboard': {'building': False, 'moving': False}, 'candle': {'building': False, 'moving': False},
    'tree house': {'building': True, 'moving': True}, 'saucer': {'building': False, 'moving': False},
    'scale': {'building': False, 'moving': False}, 'harmonica': {'building': False, 'moving': False},
    'kettle': {'building': False, 'moving': False}, 'fox': {'building': False, 'moving': True},
    'microwave': {'building': False, 'moving': False}, 'pen': {'building': False, 'moving': True},
    'treadmill': {'building': False, 'moving': False}, 'earrings': {'building': False, 'moving': False},
    'human body': {'building': False, 'moving': True}, 'knife': {'building': False, 'moving': False},
    'chest of drawers': {'building': False, 'moving': True}, 'flute': {'building': False, 'moving': False},
    'pasta': {'building': False, 'moving': False}, 'bidet': {'building': False, 'moving': False},
    'human ear': {'building': False, 'moving': True}, 'beaker': {'building': False, 'moving': False},
    'whiteboard': {'building': False, 'moving': False}, 'golf ball': {'building': False, 'moving': True},
    'shrimp': {'building': False, 'moving': True}, 'hair spray': {'building': False, 'moving': False},
    'human eye': {'building': False, 'moving': True}, 'glasses': {'building': False, 'moving': False},
    'heater': {'building': False, 'moving': False}, 'reptile': {'building': False, 'moving': True},
    'tin can': {'building': False, 'moving': False}, 'seat belt': {'building': False, 'moving': True},
    'stop sign': {'building': False, 'moving': False}, 'coffeemaker': {'building': False, 'moving': False},
    'tableware': {'building': False, 'moving': False}, 'mobile phone': {'building': False, 'moving': False},
    'syringe': {'building': False, 'moving': False}, 'chime': {'building': False, 'moving': False},
    'fashion accessory': {'building': False, 'moving': True}, 'human leg': {'building': False, 'moving': True},
    'flying disc': {'building': False, 'moving': False}, 'alpaca': {'building': False, 'moving': True},
    'submarine': {'building': False, 'moving': False}, 'sock': {'building': False, 'moving': True},
    'wine rack': {'building': False, 'moving': False}, 'winter melon': {'building': False, 'moving': False},
    'can opener': {'building': False, 'moving': True}, 'harpsichord': {'building': False, 'moving': False},
    'oyster': {'building': False, 'moving': True}, 'suit': {'building': False, 'moving': True},
    'coffee cup': {'building': False, 'moving': False}, 'fork': {'building': False, 'moving': False},
    'jug': {'building': False, 'moving': False}, 'bus': {'building': False, 'moving': False},
    'cassette deck': {'building': False, 'moving': False}, 'pitcher': {'building': False, 'moving': True},
    'tripod': {'building': False, 'moving': False}, 'diaper': {'building': False, 'moving': True},
    'helicopter': {'building': False, 'moving': False}, 'kitchen utensil': {'building': False, 'moving': False},
    'turtle': {'building': False, 'moving': True}, 'kitchenware': {'building': False, 'moving': False},
    'penguin': {'building': False, 'moving': True}, 'football': {'building': False, 'moving': False},
    'skull': {'building': False, 'moving': False}, 'land vehicle': {'building': False, 'moving': True},
    'strawberry': {'building': False, 'moving': False}, 'christmas tree': {'building': False, 'moving': True},
    'cello': {'building': False, 'moving': False}, 'suitcase': {'building': False, 'moving': False},
    'cake': {'building': False, 'moving': False}, 'sports equipment': {'building': False, 'moving': True},
    'toilet': {'building': False, 'moving': False}, 'deer': {'building': False, 'moving': True},
    'kitchen knife': {'building': False, 'moving': False}, 'pig': {'building': False, 'moving': True},
    'trombone': {'building': False, 'moving': False}, 'studio couch': {'building': False, 'moving': False},
    'human face': {'building': False, 'moving': True}, 'cream': {'building': False, 'moving': False},
    'serving tray': {'building': False, 'moving': False}, 'lemon': {'building': False, 'moving': False},
    'peach': {'building': False, 'moving': True}, 'washing machine': {'building': False, 'moving': True},
    'countertop': {'building': False, 'moving': False}, 'boot': {'building': False, 'moving': False},
    'book': {'building': False, 'moving': False}, 'tie': {'building': False, 'moving': True},
    'hippopotamus': {'building': False, 'moving': True}, 'tart': {'building': False, 'moving': True},
    'frisbee': {'building': False, 'moving': False}, 'pineapple': {'building': False, 'moving': False},
    'pear': {'building': False, 'moving': False}, 'insect': {'building': False, 'moving': True},
    'paper cutter': {'building': False, 'moving': True}, 'building': {'building': True, 'moving': False},
    'tiger': {'building': False, 'moving': True}, 'remote': {'building': False, 'moving': False},
    'adhesive tape': {'building': False, 'moving': False}, 'potato': {'building': False, 'moving': False},
    'band-aid': {'building': False, 'moving': False}, 'flowerpot': {'building': False, 'moving': False},
    'jacket': {'building': False, 'moving': True}, 'parking meter': {'building': False, 'moving': False},
    'stethoscope': {'building': False, 'moving': False}, 'platter': {'building': False, 'moving': False},
    'window blind': {'building': False, 'moving': False}}
