"""
THIS SCRIPT SHOWCASES THE RESULTS GENERATED BY THE BRAIN AS QUESTIONS COME IN.
"""

import argparse
import json
from pathlib import Path
from tempfile import TemporaryDirectory

from tqdm import tqdm

from cltl.brain.long_term_memory import LongTermMemory
from cltl.brain.utils.base_cases import questions
from cltl.brain.utils.helper_functions import brain_response_to_json


def main(log_path):
    # Create brain connection
    brain = LongTermMemory(address="http://localhost:7200/repositories/sandbox",
                           log_dir=log_path,
                           clear_all=False)

    data = []
    for capsule in tqdm(questions):
        # Add information to the brain
        response = brain.query_brain(capsule)
        if not response['response']:
            print("No response")

        print(f"\n{capsule['triple']}\n---------------------------------------------------------------\n\n")

        response_json = brain_response_to_json(response)
        data.append(response_json)

    f = open("./capsules/questions-responses.json", "w")
    json.dump(data, f)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Carl-Leolani scenario')
    parser.add_argument('--logs', type=str,
                        help="Directory to store the brain log files. Must be specified to persist the log files.")
    args, _ = parser.parse_known_args()

    if args.logs:
        main(Path(args.logs))
    else:
        with TemporaryDirectory(prefix="brain-log") as log_path:
            main(Path(log_path))
