"""
THIS SCRIPT SHOWCASES THE RESULTS GENERATED BY THE BRAIN AS QUESTIONS COME IN.
"""

import argparse
from pathlib import Path
from tempfile import TemporaryDirectory

from tqdm import tqdm

from cltl.brain.long_term_memory import LongTermMemory
from cltl.brain.utils.base_cases import questions


def main(log_path):
    # Create brain connection
    brain = LongTermMemory(address="http://localhost:7200/repositories/sandbox",
                           log_dir=log_path,
                           clear_all=False)

    for capsule in tqdm(questions):
        # Add information to the brain
        response = brain.query_brain(capsule)
        if not response['response']:
            print("No response")

        print(f"\n{capsule['triple']}\n---------------------------------------------------------------\n\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Carl-Leolani scenario')
    parser.add_argument('--logs', type=str,
                        help="Directory to store the brain log files. Must be specified to persist the log files.")
    args, _ = parser.parse_known_args()

    if args.logs:
        main(Path(args.logs))
    else:
        with TemporaryDirectory(prefix="brain-log") as log_path:
            main(Path(log_path))
