PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select ?p where {
    ?p rdf:type owl:ObjectProperty .
    FILTER (STRSTARTS(str(?p), STR(n2mu:))) .
}
ORDER BY str(?p)