PREFIX n2mu: <http://cltl.nl/leolani/n2mu/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX grasp: <http://groundedannotationframework.org/grasp#>
PREFIX gaf: <http://groundedannotationframework.org/gaf#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>

select ?label (DISTINCT GROUP_CONCAT(?type;separator="|") as ?types) ?date ?authorlabel
where {
    BIND(<%s> AS ?p) .
    BIND(<%s> AS ?o) .

    GRAPH ?g {
        ?s ?p ?o .
    } .

    ?s rdfs:label ?label .
    ?s rdf:type ?type .
    FILTER (regex(str(?type), "n2mu")) .

    FILTER (?s != <%s> )

    ?g gaf:denotedBy ?m .
    ?m prov:wasDerivedFrom ?utt .

    ?chat sem:hasSubEvent ?utt .
    ?context sem:hasEvent ?chat .
    ?context sem:hasBeginTimeStamp ?d .
    ?d rdfs:label ?date .

    ?m grasp:wasAttributedTo ?author .
    ?author rdfs:label ?authorlabel .

}
GROUP BY ?label ?date ?authorlabel